### ISSUE TITLE
No connection via external URL

### ISSUE THREAD

**Issue by jankete** [gcorgnet/sensor.emby_upcoming_media#14]
## Version of the custom_component
0.3.4

## Configuration

```
sensor:
  - platform: emby_upcoming_media
    api_key: !secret emby_api_key
    user_id: !secret emby_user_id
    host: external.url # without 'https://' or
    port: 443 # https://external.url:443 workes fine in browser
    ssl: true
    max: 5
    use_backdrop: trueyaml
```
## Log entries

```
Error while setting up emby_upcoming_media platform for sensor
Error fetching Emby data: 404
Unable to register emby client.
```

## Describe the bug
When I use my external URL, the sensor doesn't work. When I use my internal IP instead, it workes. As you can see in Debug log, there is an additional "/" between url and port, which is not part of my configuration an seems to be added automaticly. 

## Debug log

```
Could not reach url https://external.url/:443/Users/abc1234/Views
```
