### ISSUE TITLE
No Emby sensor

### ISSUE THREAD

**Issue by jgeorge1983** [gcorgnet/sensor.emby_upcoming_media#15]
Hey all,

I may be going crazy, but I have configured my YAML and it seems correct, HomeAssistant code check confirms its correct.  But there is no emby sensor in my entities?

**Comment by kingy444** [comment]
have you checked your sensor is actually sensor.sensor.emby_latest_movie

Given the name of your include filter i would expect sensor.emby_latest_movies (note only one sensor and the additional s on the end)

if you have a Tv Shows library that sensor would be sensor.emby_latest_tv_shows

**Comment by jgeorge1983** [comment]
Thanks Christoph, i have had this working now.  I had an error in my logs that when i logged into it the fix was obvious.  From memory there was another sensor before these which was stoping the config from moving on.  Anyways the below is that i have for my media card

```
type: custom:upcoming-media-card
entity: sensor.emby_latest_movies
title: Movies
```

```
type: custom:upcoming-media-card
entity: sensor.emby_latest_tv
title: Latest TV
```


and this is what i have in my config.yaml

```
- platform: emby_upcoming_media
  api_key: XXXXXXXXXXXXXXXXXXX
  user_id: XXXXXXXXXXXXXXXXXXX
  host: XXXXXXXXXXXXXXXXXXX
  port: XXXX
  ssl: False
  max: 5
  use_backdrop: true
  include:
  - Movies
  - TV
```
And that all works now, hope that helps
