### ISSUE TITLE
no fanart json tag when use_backdrop_enabled

### ISSUE THREAD

**Issue by joggs** [gcorgnet/sensor.emby_upcoming_media#26]
## Configuration

```yaml
type: custom:upcoming-media-card
entity: sensor.emby_latest_movies
image_style: fanart
title: Movies


data: [{"title_default": "$title", "line1_default": "$release", "line2_default": "$genres", "line3_default": "$rating - $runtime", "line4_default": "$studio", "icon": "mdi:arrow-down-bold"}, {"title": "The Invitation", "officialrating": "", "release": 2022, "airdate": "2022-10-06T16:12:13.179421", "studio": "Mid Atlantic Films", "genres": "Horror, Thriller", "runtime": 105.83573333333334, "poster": "http://192.168.0.40:8096/Items/616771/Images/Backdrop?maxHeight=360&maxWidth=640&quality=90", "rating": "\u2605 5.4"},


Add your logs here.

```
2022-10-06 16:12:13.261 INFO (SyncWorker_2) [homeassistant.loader] Loaded emby from homeassistant.components.emby
2022-10-06 16:12:38.514 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.emby
2022-10-06 16:12:38.541 INFO (MainThread) [pyemby.server] Latching onto an existing event loop.
2022-10-06 16:12:53.621 INFO (MainThread) [pyemby.server] Emby client registered!, Id: 90520743603948
2022-10-06 16:13:19.910 ERROR (MainThread) [frontend.js.latest.202210050] https://ha.xx/lovelace-home/embynew:0:0 Uncaught

## Describe the bug

When you set  use_backdrop_enabled to true, I understand it as that you can use the backdrop image from emby for the upcoming card that is set to fanart mode. If that is the case, the upcoming-card expects a fanart json tag and not a poster tag. So you should set the tag to fanart instead of poster when you set use_backdrop_enabled to true

Docs for the upcoming card: https://github.com/custom-cards/upcoming-media-card:

## Debug log

```text

Add your logs here.

```
